# Generated by Django 4.2.3 on 2023-11-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_attribute_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnsiUser',
            new_name='User',
        ),
    ]
